namespace EsilvaSoft.SlopStudio.Desktop.ViewModels;

public sealed partial class LocalizationViewModel
{
    /// <summary>Native agent chat, settings and approval texts (phase 7, lote 6). Order: key, en, pt-BR, es, zh-CN.</summary>
    private static readonly (string Key, string En, string Pt, string Es, string Zh)[] AgentTranslations =
    [
        ("agentPanelTitle", "AI Agent", "Agente IA", "Agente IA", "AI 智能体"),
        ("agentProvider", "Provider", "Provider", "Proveedor", "提供程序"),
        ("agentModel", "Model", "Modelo", "Modelo", "模型"),
        ("agentConfigure", "Configure…", "Configurar…", "Configurar…", "配置…"),
        ("agentDestinationLocal", "Local", "Local", "Local", "本地"),
        ("agentDestinationExternal", "External", "Externo", "Externo", "外部"),
        ("agentDestinationLocalHint", "Processed on this machine; nothing is sent elsewhere.", "Processado nesta máquina; nada é enviado para fora.", "Se procesa en este equipo; no se envía nada fuera.", "在本机处理；不会向外发送任何内容。"),
        ("agentDestinationExternalHint", "The message and the authorized context are sent to the provider's external service.", "A mensagem e o contexto autorizado são enviados ao serviço externo do provider.", "El mensaje y el contexto autorizado se envían al servicio externo del proveedor.", "消息和已授权的上下文将发送到提供程序的外部服务。"),
        ("agentFixedContext", "Fixed tab context: {0}", "Contexto fixo da aba: {0}", "Contexto fijo de la pestaña: {0}", "标签页固定上下文：{0}"),
        ("agentNoTabContext", "tab without a connection", "aba sem conexão definida", "pestaña sin conexión", "标签页未设置连接"),
        ("agentFixedContextHint", "Changing the Explorer selection does not change this context.", "Mudar a seleção do Explorer não altera este contexto.", "Cambiar la selección del Explorador no altera este contexto.", "更改资源管理器中的选择不会改变此上下文。"),
        ("agentContextScope", "Context to share", "Contexto a compartilhar", "Contexto que se compartirá", "要共享的上下文"),
        ("agentScopeNone", "None — message only", "Nenhum — somente a mensagem", "Ninguno — solo el mensaje", "无 — 仅消息"),
        ("agentScopeMetadata", "Metadata only — logical connection and namespace", "Somente metadados — conexão lógica e namespace", "Solo metadatos — conexión lógica y namespace", "仅元数据 — 逻辑连接和命名空间"),
        ("agentScopeSelection", "Editor selection — excerpt confirmed in the preview", "Seleção do editor — trecho confirmado na prévia", "Selección del editor — fragmento confirmado en la vista previa", "编辑器选区 — 在预览中确认的片段"),
        ("agentConsentExternal", "I authorize sending the message and the chosen context to {0} (External) in this session.", "Autorizo enviar a mensagem e o contexto escolhido para {0} (Externo) nesta sessão.", "Autorizo enviar el mensaje y el contexto elegido a {0} (Externo) en esta sesión.", "我授权在本会话中将消息和所选上下文发送到 {0}（外部）。"),
        ("agentConsentHint", "Connecting an account or saving a key does not authorize sending data.", "Conectar a conta ou salvar a chave não autoriza envio de dados.", "Conectar la cuenta o guardar la clave no autoriza el envío de datos.", "连接账户或保存密钥并不授权发送数据。"),
        ("agentComposer", "Message to the agent", "Mensagem para o agente", "Mensaje para el agente", "发送给智能体的消息"),
        ("agentComposerPlaceholder", "Describe what you need. Enter adds a line; Ctrl+Enter reviews and sends.", "Descreva o que precisa. Enter quebra linha; Ctrl+Enter revisa e envia.", "Describa lo que necesita. Enter agrega una línea; Ctrl+Enter revisa y envía.", "描述您的需求。Enter 换行；Ctrl+Enter 预览并发送。"),
        ("agentComposerShortcut", "Ctrl+Enter works only while the message box has focus.", "Ctrl+Enter vale somente com o foco na caixa de mensagem.", "Ctrl+Enter solo funciona con el foco en el cuadro de mensaje.", "仅当消息框获得焦点时 Ctrl+Enter 才生效。"),
        ("agentReview", "Review send", "Revisar envio", "Revisar envío", "预览发送"),
        ("agentSend", "Send", "Enviar", "Enviar", "发送"),
        ("agentEdit", "Edit", "Editar", "Editar", "编辑"),
        ("agentCancelTurn", "Cancel run", "Cancelar execução", "Cancelar ejecución", "取消运行"),
        ("agentPreviewTitle", "Send preview", "Prévia do envio", "Vista previa del envío", "发送预览"),
        ("agentPreviewDestination", "Destination: {0} · {1}", "Destino: {0} · {1}", "Destino: {0} · {1}", "目标：{0} · {1}"),
        ("agentPreviewScope", "Scope: {0}", "Escopo: {0}", "Alcance: {0}", "范围：{0}"),
        ("agentPreviewNamespace", "Namespace: {0}", "Namespace: {0}", "Namespace: {0}", "命名空间：{0}"),
        ("agentPreviewContextEmpty", "No context besides the message.", "Nenhum contexto além da mensagem.", "Ningún contexto además del mensaje.", "除消息外无其他上下文。"),
        ("agentPreviewStale", "The preview was discarded because the message, scope, provider or tab context changed.", "A prévia foi descartada porque mensagem, escopo, provider ou contexto da aba mudaram.", "La vista previa se descartó porque cambió el mensaje, el alcance, el proveedor o el contexto de la pestaña.", "由于消息、范围、提供程序或标签页上下文已更改，预览已被丢弃。"),
        ("agentPreviewSelectionEmpty", "The editor has no selection; select an excerpt or choose another scope.", "O editor não tem seleção; selecione um trecho ou escolha outro escopo.", "El editor no tiene selección; seleccione un fragmento o elija otro alcance.", "编辑器中没有选区；请选择一段内容或选择其他范围。"),
        ("agentHistory", "Conversation history", "Histórico da conversa", "Historial de la conversación", "会话历史"),
        ("agentRoleUser", "You", "Você", "Usted", "您"),
        ("agentRoleAgent", "Agent", "Agente", "Agente", "智能体"),
        ("agentStreaming", "generating…", "gerando…", "generando…", "生成中…"),
        ("agentToolUnknown", "Unrecognized tool", "Ferramenta não reconhecida", "Herramienta no reconocida", "无法识别的工具"),
        ("agentToolRequested", "Requested", "Solicitada", "Solicitada", "已请求"),
        ("agentToolRunning", "Running", "Em execução", "En ejecución", "运行中"),
        ("agentToolSucceeded", "Completed", "Concluída", "Completada", "已完成"),
        ("agentToolFailed", "Failed", "Falhou", "Falló", "失败"),
        ("agentToolDenied", "Denied", "Negada", "Denegada", "已拒绝"),
        ("agentToolCancelled", "Cancelled — not executed", "Cancelada — não executada", "Cancelada — no ejecutada", "已取消 — 未执行"),
        ("agentToolOutcomeUnknown", "Uncertain outcome — may have run", "Resultado incerto — pode ter executado", "Resultado incierto — puede haberse ejecutado", "结果不确定 — 可能已执行"),
        ("agentToolCard", "Tool {0}", "Ferramenta {0}", "Herramienta {0}", "工具 {0}"),
        ("agentToolStatusLine", "{0} · {1}", "{0} · {1}", "{0} · {1}", "{0} · {1}"),
        ("agentToolDuration", "{0} ms", "{0} ms", "{0} ms", "{0} 毫秒"),
        ("agentToolCode", "code {0}", "código {0}", "código {0}", "代码 {0}"),
        ("agentToolDestination", "Destination: {0}", "Destino: {0}", "Destino: {0}", "目标：{0}"),
        ("agentToolTarget", "Target: {0}", "Destino: {0}", "Destino: {0}", "目标：{0}"),
        ("agentApprovalPending", "Waiting for approval", "Aguardando aprovação", "Esperando aprobación", "等待批准"),
        ("agentApprovalReview", "Review approval…", "Revisar aprovação…", "Revisar aprobación…", "审阅批准…"),
        ("agentApprovalGranted", "Approved once", "Aprovada uma vez", "Aprobada una vez", "已批准一次"),
        ("agentApprovalDenied", "Rejected — not executed", "Rejeitada — nada foi executado", "Rechazada — no se ejecutó nada", "已拒绝 — 未执行任何操作"),
        ("agentApprovalExpiredCard", "Expired — nothing was executed", "Expirada — nada foi executado", "Caducada — no se ejecutó nada", "已过期 — 未执行任何操作"),
        ("agentApprovalCancelledCard", "Closed with the turn — nothing was executed", "Encerrada com o turno — nada foi executado", "Cerrada con el turno — no se ejecutó nada", "随轮次关闭 — 未执行任何操作"),
        ("agentApprovalCardTitle", "Approval", "Aprovação", "Aprobación", "批准"),
        ("agentStateUnavailable", "AI Agent is unavailable in this version. The editor, Explorer and queries keep working.", "Agente IA indisponível nesta versão. O editor, o Explorer e as consultas continuam funcionando.", "El Agente IA no está disponible en esta versión. El editor, el Explorador y las consultas siguen funcionando.", "此版本中 AI 智能体不可用。编辑器、资源管理器和查询仍可正常使用。"),
        ("agentStateNoProvider", "No provider available. Configure a provider to chat; the IDE keeps working.", "Nenhum provider disponível. Configure um provider para conversar; a IDE continua operacional.", "No hay proveedores disponibles. Configure uno para conversar; el IDE sigue operativo.", "没有可用的提供程序。请配置提供程序后再对话；IDE 仍可正常使用。"),
        ("agentStateProviderUnavailable", "{0} unavailable: {1}", "{0} indisponível: {1}", "{0} no disponible: {1}", "{0} 不可用：{1}"),
        ("agentStateNotAuthenticated", "{0} needs an API key. Use Configure…; saving the key does not send data.", "{0} requer uma chave de API. Use Configurar…; salvar a chave não envia dados.", "{0} requiere una clave de API. Use Configurar…; guardar la clave no envía datos.", "{0} 需要 API 密钥。请使用“配置…”；保存密钥不会发送数据。"),
        ("agentStateCredentialExpired", "The credential for {0} expired or is invalid. Use Configure… to reconnect.", "A credencial de {0} expirou ou é inválida. Use Configurar… para reconectar.", "La credencial de {0} caducó o no es válida. Use Configurar… para reconectar.", "{0} 的凭据已过期或无效。请使用“配置…”重新连接。"),
        ("agentStateVaultUnavailable", "The system vault is unavailable; {0} cannot be used now.", "Cofre do sistema indisponível; {0} não pode ser usado agora.", "El almacén del sistema no está disponible; {0} no se puede usar ahora.", "系统保管库不可用；目前无法使用 {0}。"),
        ("agentStateReady", "Ready. Choose the context and review the send.", "Pronto. Escolha o contexto e revise o envio.", "Listo. Elija el contexto y revise el envío.", "就绪。请选择上下文并预览发送内容。"),
        ("agentStateConsentRequired", "Authorize the external destination to send.", "Autorize o destino externo para enviar.", "Autorice el destino externo para enviar.", "请授权外部目标后再发送。"),
        ("agentStateReviewing", "Review the preview. Nothing has been sent yet.", "Revise a prévia. Nada foi enviado ainda.", "Revise la vista previa. Todavía no se envió nada.", "请检查预览。尚未发送任何内容。"),
        ("agentStateConnecting", "Connecting to {0}…", "Conectando a {0}…", "Conectando a {0}…", "正在连接到 {0}…"),
        ("agentStateGenerating", "Generating a response…", "Gerando resposta…", "Generando respuesta…", "正在生成回复…"),
        ("agentStateWaitingTool", "Waiting for a tool…", "Aguardando ferramenta…", "Esperando una herramienta…", "正在等待工具…"),
        ("agentStateWaitingApproval", "Waiting for your approval.", "Aguardando sua aprovação.", "Esperando su aprobación.", "正在等待您的批准。"),
        ("agentStateCancelling", "Cancelling…", "Cancelando…", "Cancelando…", "正在取消…"),
        ("agentStateCompleted", "Completed.", "Concluído.", "Completado.", "已完成。"),
        ("agentStateCancelled", "Turn cancelled. Operations already sent may have been applied; there is no rollback.", "Turno cancelado. Operações já enviadas podem ter sido aplicadas; não há rollback.", "Turno cancelado. Las operaciones ya enviadas pueden haberse aplicado; no hay reversión.", "轮次已取消。已发送的操作可能已被应用；不会回滚。"),
        ("agentStateOutcomeUnknown", "Uncertain outcome: an interruption or tool could not be confirmed. Check the target before repeating.", "Resultado incerto: a interrupção ou uma ferramenta não pôde ser confirmada. Verifique o destino antes de repetir.", "Resultado incierto: no se pudo confirmar la interrupción o una herramienta. Compruebe el destino antes de repetir.", "结果不确定：无法确认中断或某个工具的结果。重复操作前请检查目标。"),
        ("agentStateTimedOut", "The turn exceeded its time limit and was closed.", "O turno excedeu o tempo limite e foi encerrado.", "El turno superó el tiempo límite y se cerró.", "该轮次超出时间限制，已关闭。"),
        ("agentStateFailed", "Agent failure ({0}). You can continue with a new message.", "Falha do agente ({0}). A conversa pode continuar com uma nova mensagem.", "Error del agente ({0}). Puede continuar con un mensaje nuevo.", "智能体失败（{0}）。您可以发送新消息继续。"),
        ("agentStateContextFailed", "The context could not be prepared ({0}). Nothing was sent.", "Não foi possível preparar o contexto ({0}). Nada foi enviado.", "No se pudo preparar el contexto ({0}). No se envió nada.", "无法准备上下文（{0}）。未发送任何内容。"),
        ("agentProviderSwitched", "New session with {0}. Nothing from the previous conversation was transferred.", "Nova sessão com {0}. Nada da conversa anterior foi transferido.", "Nueva sesión con {0}. No se transfirió nada de la conversación anterior.", "已与 {0} 建立新会话。未转移先前会话的任何内容。"),
        ("agentEmptyTitle", "Chat with the agent about this tab", "Converse com o agente sobre esta aba", "Converse con el agente sobre esta pestaña", "就此标签页与智能体对话"),
        ("agentEmptyBody", "The agent never runs queries when you open collections or send messages. Tools and writes go through permissions and approval.", "O agente não executa consultas ao abrir coleções nem ao enviar mensagens. Ferramentas e escritas passam por permissões e aprovação.", "El agente no ejecuta consultas al abrir colecciones ni al enviar mensajes. Las herramientas y escrituras pasan por permisos y aprobación.", "打开集合或发送消息时，智能体不会执行查询。工具和写入操作需经过权限和批准。"),
        ("agentApprovalTitle", "Approve agent action", "Aprovar ação do agente", "Aprobar acción del agente", "批准智能体操作"),
        ("agentApprovalIntro", "The agent requested an action that needs your approval. Agent text never approves anything.", "O agente solicitou uma ação que exige sua aprovação. Texto do agente não aprova nada.", "El agente solicitó una acción que requiere su aprobación. El texto del agente no aprueba nada.", "智能体请求了需要您批准的操作。智能体的文本不能批准任何操作。"),
        ("agentApprovalTool", "Tool", "Ferramenta", "Herramienta", "工具"),
        ("agentApprovalTarget", "Connection › database › collection", "Conexão › banco › coleção", "Conexión › base de datos › colección", "连接 › 数据库 › 集合"),
        ("agentApprovalFilter", "Filter / identity", "Filtro / identidade", "Filtro / identidad", "过滤器 / 标识"),
        ("agentApprovalChange", "Proposed change", "Mudança proposta", "Cambio propuesto", "拟议更改"),
        ("agentApprovalNoChange", "No data change (read).", "Sem mudança de dados (leitura).", "Sin cambio de datos (lectura).", "无数据更改（读取）。"),
        ("agentApprovalLimit", "Affected limit", "Limite afetado", "Límite afectado", "影响上限"),
        ("agentApprovalLimitValue", "Up to {0} document(s)", "Até {0} documento(s)", "Hasta {0} documento(s)", "最多 {0} 个文档"),
        ("agentApprovalLimitUnknown", "Not informed", "Não informado", "No informado", "未提供"),
        ("agentApprovalRisk", "Risk", "Risco", "Riesgo", "风险"),
        ("agentRiskReadOnly", "Read-only", "Somente leitura", "Solo lectura", "只读"),
        ("agentRiskWrite", "Write", "Escrita", "Escritura", "写入"),
        ("agentRiskDestructive", "Destructive", "Destrutiva", "Destructiva", "破坏性"),
        ("agentApprovalExpiresIn", "Expires in {0}", "Expira em {0}", "Caduca en {0}", "{0} 后过期"),
        ("agentApprovalExpired", "Approval expired. Nothing was executed; ask the agent for a new proposal.", "Aprovação expirada. Nada foi executado; peça ao agente uma nova proposta.", "Aprobación caducada. No se ejecutó nada; pida al agente una nueva propuesta.", "批准已过期。未执行任何操作；请让智能体重新提出建议。"),
        ("agentApprovalLoading", "Verifying approval details…", "Verificando detalhes da aprovação…", "Verificando los detalles de la aprobación…", "正在验证批准详情…"),
        ("agentApprovalDetailsMissing", "The details of this approval could not be verified. Reject it; nothing will be executed.", "Os detalhes desta aprovação não puderam ser verificados. Rejeite; nada será executado.", "No se pudieron verificar los detalles de esta aprobación. Recházela; no se ejecutará nada.", "无法验证此批准的详细信息。请拒绝；不会执行任何操作。"),
        ("agentApprovalDestructiveConfirm", "To confirm the destructive action, type the collection name: {0}", "Para confirmar a ação destrutiva, digite o nome da coleção: {0}", "Para confirmar la acción destructiva, escriba el nombre de la colección: {0}", "要确认破坏性操作，请输入集合名称：{0}"),
        ("agentApprovalDestructiveInput", "Collection name to confirm", "Nome da coleção para confirmar", "Nombre de la colección para confirmar", "用于确认的集合名称"),
        ("agentApprovalReject", "Reject", "Rejeitar", "Rechazar", "拒绝"),
        ("agentApprovalApproveOnce", "Approve once", "Aprovar uma vez", "Aprobar una vez", "批准一次"),
        ("agentApprovalRejectHint", "Reject (Esc) — nothing is executed", "Rejeitar (Esc) — nada é executado", "Rechazar (Esc) — no se ejecuta nada", "拒绝（Esc）— 不执行任何操作"),
        ("agentApprovalApproveHint", "Approves only this proposal; any change needs a new approval.", "Aprova somente esta proposta; qualquer alteração exige nova aprovação.", "Aprueba solo esta propuesta; cualquier cambio requiere una nueva aprobación.", "仅批准此提议；任何更改都需要重新批准。"),
        ("agentApprovalSubmitting", "Delivering the decision…", "Entregando a decisão…", "Entregando la decisión…", "正在提交决定…"),
        ("agentApprovalGrantedNotice", "Approved once. The result will appear in the conversation.", "Aprovada uma vez. O resultado aparecerá na conversa.", "Aprobada una vez. El resultado aparecerá en la conversación.", "已批准一次。结果将显示在会话中。"),
        ("agentApprovalRejectedNotice", "Rejected. Nothing was executed.", "Rejeitada. Nada foi executado.", "Rechazada. No se ejecutó nada.", "已拒绝。未执行任何操作。"),
        ("agentApprovalClosedByRuntime", "This approval was closed ({0}). Nothing was executed.", "Esta aprovação foi encerrada ({0}). Nada foi executado.", "Esta aprobación se cerró ({0}). No se ejecutó nada.", "此批准已关闭（{0}）。未执行任何操作。"),
        ("agentApprovalFailed", "The decision could not be delivered ({0}). Nothing was approved.", "A decisão não pôde ser entregue ({0}). Nada foi aprovado.", "No se pudo entregar la decisión ({0}). No se aprobó nada.", "无法提交决定（{0}）。未批准任何操作。"),
        ("agentApprovalCancelNotice", "Cancelling the run does not revert operations already sent.", "Cancelar a execução não reverte operações já enviadas.", "Cancelar la ejecución no revierte las operaciones ya enviadas.", "取消运行不会撤销已发送的操作。"),
        ("agentSettingsTitle", "Configure agents", "Configurar agentes", "Configurar agentes", "配置智能体"),
        ("agentSettingsIntro", "Providers and authentication available in this version. Configuring an account does not authorize sending data: each send needs an explicit context and destination in the chat.", "Providers e autenticação disponíveis nesta versão. Configurar uma conta não autoriza envio de dados: cada envio exige escolha explícita de contexto e destino no chat.", "Proveedores y autenticación disponibles en esta versión. Configurar una cuenta no autoriza el envío de datos: cada envío requiere elegir explícitamente contexto y destino en el chat.", "此版本中可用的提供程序和身份验证。配置账户并不授权发送数据：每次发送都需要在聊天中明确选择上下文和目标。"),
        ("agentSettingsProviders", "Registered providers", "Providers registrados", "Proveedores registrados", "已注册的提供程序"),
        ("agentSettingsNoProviders", "No provider is registered. The AI Agent stays unavailable; the IDE keeps working.", "Nenhum provider registrado. O Agente IA fica indisponível; a IDE continua operacional.", "No hay proveedores registrados. El Agente IA queda no disponible; el IDE sigue operativo.", "未注册任何提供程序。AI 智能体不可用；IDE 仍可正常使用。"),
        ("agentSettingsAvailable", "Available", "Disponível", "Disponible", "可用"),
        ("agentSettingsAvailability", "Availability", "Disponibilidade", "Disponibilidad", "可用性"),
        ("agentSettingsUnavailable", "Unavailable", "Indisponível", "No disponible", "不可用"),
        ("agentSettingsAuth", "Authentication", "Autenticação", "Autenticación", "身份验证"),
        ("agentAuthNone", "No account (local)", "Sem conta (local)", "Sin cuenta (local)", "无需账户（本地）"),
        ("agentAuthApiKey", "API key", "Chave de API", "Clave de API", "API 密钥"),
        ("agentSettingsNoAuthMethods", "No official authentication method is available for this provider.", "Nenhum método de autenticação oficial disponível para este provider.", "No hay un método de autenticación oficial disponible para este proveedor.", "此提供程序没有可用的官方身份验证方法。"),
        ("agentSettingsApiKeyPlaceholder", "Paste the key; it is not shown after saving", "Cole a chave; ela não é exibida depois de salva", "Pegue la clave; no se muestra después de guardarla", "粘贴密钥；保存后不会再显示"),
        ("agentSettingsSaveKey", "Save key to vault", "Salvar chave no cofre", "Guardar clave en el almacén", "将密钥保存到保管库"),
        ("agentSettingsRemoveKey", "Remove key", "Remover chave", "Quitar clave", "删除密钥"),
        ("agentSettingsVaultNote", "The key is written only to the system vault by explicit action; never to files, logs or the workspace.", "A chave é gravada somente no cofre do sistema por ação explícita; nunca em arquivos, logs ou no workspace.", "La clave se escribe solo en el almacén del sistema mediante una acción explícita; nunca en archivos, registros ni en el workspace.", "密钥只会通过显式操作写入系统保管库；绝不会写入文件、日志或工作区。"),
        ("agentAuthStateNotRequired", "No account required", "Não requer conta", "No requiere cuenta", "无需账户"),
        ("agentAuthStateNotConfigured", "Key not configured", "Chave não configurada", "Clave no configurada", "未配置密钥"),
        ("agentAuthStateConfigured", "Key configured in the vault", "Chave configurada no cofre", "Clave configurada en el almacén", "密钥已配置在保管库中"),
        ("agentAuthStateInvalid", "Invalid key — save a new key", "Chave inválida — salve uma nova chave", "Clave no válida — guarde una nueva", "密钥无效 — 请保存新密钥"),
        ("agentAuthStateExpired", "Credential expired — reconnect", "Credencial expirada — reconecte", "Credencial caducada — vuelva a conectar", "凭据已过期 — 请重新连接"),
        ("agentAuthStateVaultUnavailable", "System vault unavailable", "Cofre do sistema indisponível", "Almacén del sistema no disponible", "系统保管库不可用"),
        ("agentAuthStateUnknown", "Credential state not reported", "Estado da credencial não informado", "Estado de la credencial no informado", "未报告凭据状态"),
        ("agentKeySaved", "Key saved to the system vault.", "Chave salva no cofre do sistema.", "Clave guardada en el almacén del sistema.", "密钥已保存到系统保管库。"),
        ("agentKeyRemoved", "Key removed from the vault.", "Chave removida do cofre.", "Clave quitada del almacén.", "已从保管库删除密钥。"),
        ("agentKeyVaultUnavailable", "System vault unavailable. The key was not saved.", "Cofre do sistema indisponível. A chave não foi salva.", "Almacén del sistema no disponible. La clave no se guardó.", "系统保管库不可用。密钥未保存。"),
        ("agentKeyCancelled", "Operation cancelled. Nothing was changed.", "Operação cancelada. Nada foi alterado.", "Operación cancelada. No se cambió nada.", "操作已取消。未进行任何更改。"),
        ("agentKeyFailed", "Vault write failed. The key was not saved.", "Falha ao gravar no cofre. A chave não foi salva.", "Error al escribir en el almacén. La clave no se guardó.", "写入保管库失败。密钥未保存。"),
        ("agentKeyRejected", "Invalid key format (empty, too long or with spaces/line breaks). Nothing was saved.", "Formato de chave inválido (vazia, longa demais ou com espaços/quebras de linha). Nada foi salvo.", "Formato de clave no válido (vacía, demasiado larga o con espacios/saltos de línea). No se guardó nada.", "密钥格式无效（为空、过长或包含空格/换行）。未保存任何内容。"),
        ("agentKeySetupUnavailable", "Key setup is unavailable in this version.", "Configuração de chave indisponível nesta versão.", "La configuración de claves no está disponible en esta versión.", "此版本中无法配置密钥。"),
        ("agentSettingsModels", "Allowed models", "Modelos permitidos", "Modelos permitidos", "允许的模型"),
        ("agentSettingsNoModels", "No model available", "Nenhum modelo disponível", "Ningún modelo disponible", "没有可用的模型"),
        ("agentSettingsCapabilities", "Capabilities", "Capacidades", "Capacidades", "功能"),
        ("agentCapabilitiesValue", "Streaming: {0} · SlopStudio tools: {1}", "Streaming: {0} · Ferramentas do SlopStudio: {1}", "Streaming: {0} · Herramientas de SlopStudio: {1}", "流式传输：{0} · SlopStudio 工具：{1}"),
        ("agentYes", "yes", "sim", "sí", "是"),
        ("agentNo", "no", "não", "no", "否"),
        ("agentSettingsDestination", "Data destination", "Destino dos dados", "Destino de los datos", "数据目标"),
        ("agentProviderItem", "{0} · {1}", "{0} · {1}", "{0} · {1}", "{0} · {1}"),
        // P7-L06-HOST: hosting in the main window, explicit availability check and startup credential report.
        ("agentPanelToggle", "AI Agent", "Agente IA", "Agente IA", "AI 智能体"),
        ("agentPanelToggleHint", "Show or hide the AI Agent panel of the active tab (Ctrl+Shift+A)", "Mostrar ou recolher o painel Agente IA da aba ativa (Ctrl+Shift+A)", "Mostrar u ocultar el panel Agente IA de la pestaña activa (Ctrl+Shift+A)", "显示或隐藏当前标签页的 AI 智能体面板（Ctrl+Shift+A）"),
        ("agentPanelClose", "Collapse the AI Agent panel (Ctrl+Shift+A)", "Recolher o painel Agente IA (Ctrl+Shift+A)", "Ocultar el panel Agente IA (Ctrl+Shift+A)", "收起 AI 智能体面板（Ctrl+Shift+A）"),
        ("agentPanelBackToEditor", "Back to the editor (Ctrl+Shift+A)", "Voltar ao editor (Ctrl+Shift+A)", "Volver al editor (Ctrl+Shift+A)", "返回编辑器（Ctrl+Shift+A）"),
        ("agentPanelBackToEditorShort", "Back to editor", "Voltar ao editor", "Volver al editor", "返回编辑器"),
        ("agentSettingsNotChecked", "Not checked", "Não verificado", "No verificado", "未检查"),
        ("agentUnavailableNotChecked", "availability not checked yet. Use Check availability; nothing is sent.", "disponibilidade ainda não verificada. Use Verificar disponibilidade; nada é enviado.", "disponibilidad aún no verificada. Use Verificar disponibilidad; no se envía nada.", "尚未检查可用性。请使用“检查可用性”；不会发送任何内容。"),
        ("agentUnavailableTimedOut", "the availability check timed out.", "a verificação de disponibilidade excedeu o tempo.", "la verificación de disponibilidad superó el tiempo límite.", "可用性检查超时。"),
        ("agentUnavailableCheckFailed", "the availability check failed.", "a verificação de disponibilidade falhou.", "la verificación de disponibilidad falló.", "可用性检查失败。"),
        ("agentRefreshProviders", "Check availability", "Verificar disponibilidade", "Verificar disponibilidad", "检查可用性"),
        ("agentRefreshProvidersHint", "Checks configuration and the system vault on this machine; it does not connect to the provider or send data.", "Verifica a configuração e o cofre do sistema nesta máquina; não conecta ao provider nem envia dados.", "Comprueba la configuración y el almacén del sistema en este equipo; no se conecta al proveedor ni envía datos.", "检查本机上的配置和系统保管库；不会连接提供程序或发送数据。"),
        ("agentRefreshFailed", "The availability check could not be completed. Nothing was sent.", "Não foi possível concluir a verificação de disponibilidade. Nada foi enviado.", "No se pudo completar la verificación de disponibilidad. No se envió nada.", "无法完成可用性检查。未发送任何内容。"),
        ("credentialRecoveryChecking", "Checking pending credential recovery…", "Verificando recuperação pendente de credenciais…", "Verificando la recuperación pendiente de credenciales…", "正在检查待恢复的凭据…"),
        ("credentialRecoveryPending", "{0} credential recovery record(s) pending in the system vault. The IDE keeps working; recovery resumes in the background.", "{0} registro(s) de recuperação de credenciais pendente(s) no cofre do sistema. A IDE continua operacional; a recuperação prossegue em segundo plano.", "{0} registro(s) de recuperación de credenciales pendiente(s) en el almacén del sistema. El IDE sigue operativo; la recuperación continúa en segundo plano.", "系统保管库中有 {0} 条待恢复的凭据记录。IDE 仍可正常使用；恢复将在后台继续。"),
        ("credentialRecoveryNone", "No pending credential recovery.", "Nenhuma recuperação de credenciais pendente.", "No hay recuperación de credenciales pendiente.", "没有待恢复的凭据。"),
        ("credentialRecoveryCancelled", "Credential recovery check cancelled.", "Verificação de recuperação de credenciais cancelada.", "Verificación de recuperación de credenciales cancelada.", "已取消凭据恢复检查。"),
        ("credentialRecoveryFailed", "Could not check pending credential recovery. Profiles and drafts were not changed.", "Não foi possível verificar a recuperação pendente de credenciais. Perfis e rascunhos não foram alterados.", "No se pudo verificar la recuperación pendiente de credenciales. No se cambiaron perfiles ni borradores.", "无法检查待恢复的凭据。配置文件和草稿未被更改。"),
    ];
}
