<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <EmbeddedResource Include="ConsoleBootstrap.js" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Jint" />
    <ProjectReference Include="../EsilvaSoft.SlopStudio.Application/EsilvaSoft.SlopStudio.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="LiteDB" />
    <PackageReference Include="MongoDB.Driver" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
</Project>
