<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../EsilvaSoft.SlopStudio.Core/EsilvaSoft.SlopStudio.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Language/mongodb-language.v1.json" LogicalName="EsilvaSoft.SlopStudio.Application.Language.mongodb-language.v1.json" />
  </ItemGroup>
</Project>
