namespace EsilvaSoft.SlopStudio.Core.Agents;

public enum AgentEventKind
{
    SessionStarted,
    MessageStarted,
    MessageDelta,
    MessageCompleted,
    ToolRequested,
    ToolStarted,
    ToolCompleted,
    ToolFailed,
    ApprovalRequested,
    ApprovalGranted,
    ApprovalDenied,
    FileChangeProposed,
    DatabaseChangeProposed,
    TaskStarted,
    TaskProgress,
    TaskCompleted,
    AgentError,
    SessionCompleted,
}

/// <summary>Turn terminal state. Cancellation never implies rollback of an operation already dispatched.</summary>
public enum AgentTurnOutcome
{
    Completed,
    Cancelled,
    Failed,
    OutcomeUnknown,
    TimedOut,
}

/// <summary>
/// Provider-neutral event. Error details are safe codes generated by the runtime. <see cref="Sequence"/> is
/// monotonic per session; each message, tool call, approval and turn receives exactly one terminal event.
/// Tool data is never copied into events; only status and safe codes.
/// </summary>
public sealed record AgentEvent(
    int ProtocolVersion,
    Guid EventId,
    AgentSessionId SessionId,
    AgentTurnId? TurnId,
    long Sequence,
    DateTimeOffset TimestampUtc,
    Guid CorrelationId,
    AgentEventKind Kind,
    string? Text = null,
    AgentTurnOutcome? Outcome = null,
    string? ErrorCode = null,
    AgentToolCallId? ToolCallId = null,
    AgentApprovalId? ApprovalId = null,
    AgentMessageId? MessageId = null,
    string? ToolName = null,
    AgentToolResultStatus? ToolStatus = null)
{
    /// <summary>
    /// Sanitized destination of a tool call's output (Local/External only, no provider or client identifier), set by
    /// the runtime on tool events from the session's destination, which derives from the provider's <c>IsLocal</c>.
    /// </summary>
    public AgentDataDestinationKind? ToolDestination { get; init; }

    /// <summary>
    /// Wall-clock deadline of an approval, set by the runtime on <see cref="AgentEventKind.ApprovalRequested"/> from its
    /// own timeout (never from provider data). Display only: the runtime enforces expiry on a monotonic clock.
    /// </summary>
    public DateTimeOffset? ApprovalExpiresAtUtc { get; init; }
}
