namespace EsilvaSoft.SlopStudio.Core.Agents;

public enum AgentEventKind
{
    SessionStarted,
    MessageStarted,
    MessageDelta,
    MessageCompleted,
    ToolRequested,
    ToolStarted,
    ToolCompleted,
    ToolFailed,
    ApprovalRequested,
    ApprovalGranted,
    ApprovalDenied,
    FileChangeProposed,
    DatabaseChangeProposed,
    TaskStarted,
    TaskProgress,
    TaskCompleted,
    AgentError,
    SessionCompleted,
}

public enum AgentTurnOutcome
{
    Completed,
    Cancelled,
    Failed,
    OutcomeUnknown,
}

/// <summary>Provider-neutral event. Error details are safe codes generated by the runtime.</summary>
public sealed record AgentEvent(
    int ProtocolVersion,
    Guid EventId,
    AgentSessionId SessionId,
    AgentTurnId? TurnId,
    long Sequence,
    DateTimeOffset TimestampUtc,
    Guid CorrelationId,
    AgentEventKind Kind,
    string? Text = null,
    AgentTurnOutcome? Outcome = null,
    string? ErrorCode = null);
